In [1]:
info_wt = pd.read_csv("info_wt.csv")
info_wt.head()

wt_num    title  score    artist    genre  chapter  reader
0       0     신의 탑   9.93       SIU  fantasy      380     982
1       1  뷰티풀 군바리   9.82  설이 / 윤성원    drama      161    2332
2       2   윈드브레이커   9.96       조용석    drama      212     550
3       3   소녀의 세계   9.98       모랑지    daily      141     355
4       5   평범한 8반   9.95       영파카    comic      213     485

In [2]:
X_data = info_wt[["genre", "title", "chapter", "reader"]]

In [3]:
import statsmodels.api as sm

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [4]:
y = info_wt[["score"]]

In [5]:
model = sm.OLS.from_formula("score ~ scale(chapter) + scale(reader) + C(genre)", info_wt)

In [6]:
result = model.fit()
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                  score   R-squared:                       0.058
Model:                            OLS   Adj. R-squared:                 -0.024
Method:                 Least Squares   F-statistic:                    0.7109
Date:                Thu, 03 May 2018   Prob (F-statistic):              0.726
Time:                        22:52:47   Log-Likelihood:                -64.974
No. Observations:                 139   AIC:                             153.9
Df Residuals:                     127   BIC:                             189.2
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Intercept                 

In [7]:
comments = pd.read_csv("comments.csv")
comments.tail()

chapter           user_id  \
735496       16  정예****(yeji****)   
735497       16  정예****(yeji****)   
735498       16  정예****(yeji****)   
735499       16  민트****(skie****)   
735500       16  이경****(jpmj****)   

                                                  comment  like  dislike  \
735496                                  나라야...포기하면 협박 하겠어     0        0   
735497                 나라야!!!니가 성윤이를 포기하면 내가 가지게 될것이야!!!!     0        1   
735498          나라하고 예진하고 성윤이를 두고 삼각 관계라면 내가 성윤이를 가지겠어!!!     0        3   
735499  태호가 왜그래?하고 얼굴들이밀때 나도 깜놀 ㅋㅋ\n전에 성윤이가 최날이랑 버스 나란...     2        0   
735500                                                  옹     1        0   

        wt_num  
735496     191  
735497     191  
735498     191  
735499     191  
735500     191

In [8]:
text_df = info_wt.merge(comments, on='wt_num')
text_df = text_df[['user_id','title','genre','comment']]
text_df.tail()

user_id  title   genre  \
735496  정예****(yeji****)  귀도호가록  action   
735497  정예****(yeji****)  귀도호가록  action   
735498  정예****(yeji****)  귀도호가록  action   
735499  민트****(skie****)  귀도호가록  action   
735500  이경****(jpmj****)  귀도호가록  action   

                                                  comment  
735496                                  나라야...포기하면 협박 하겠어  
735497                 나라야!!!니가 성윤이를 포기하면 내가 가지게 될것이야!!!!  
735498          나라하고 예진하고 성윤이를 두고 삼각 관계라면 내가 성윤이를 가지겠어!!!  
735499  태호가 왜그래?하고 얼굴들이밀때 나도 깜놀 ㅋㅋ\n전에 성윤이가 최날이랑 버스 나란...  
735500                                                  옹

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(text_df.comment, text_df.title, \
                                                    test_size = 0.1, random_state =1)
#10%를 테스트로
X_train=X_train.values.astype('U')
X_test=X_test.values.astype('U')

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB

a = Pipeline([
    ('vect', TfidfVectorizer()),
    ('clf', MultinomialNB(alpha=0.01)) # alpha -> 스무딩
])
model = a.fit(X_train, y_train)

In [12]:
y_pred = model.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix, classification_report 
confusion_matrix(y_test, y_pred)

array([[ 25,   1,   0, ...,   0,   7,   0],
       [  0, 163,   0, ...,   0,  16,   0],
       [  0,   1,   9, ...,   0,   2,   0],
       ...,
       [  0,   0,   0, ...,  16,   0,   0],
       [  0,   4,   0, ...,   0, 891,   0],
       [  0,   1,   0, ...,   0,  10, 172]])

In [14]:
print(classification_report(y_test, y_pred))

                 precision    recall  f1-score   support

        10월 28일       0.74      0.12      0.20       211
       5kg을 위하여       0.55      0.25      0.34       661
       Doll 체인지       1.00      0.09      0.16       104
           가담항설       0.76      0.23      0.35       394
    가우스전자 시즌3~4       0.70      0.17      0.28       134
      간 떨어지는 동거       0.71      0.28      0.40       468
           간질간질       1.00      0.06      0.12        31
            감염자       0.73      0.13      0.23       163
      갓 오브 하이스쿨       0.78      0.43      0.55       555
           강변살다       1.00      0.13      0.24        15
        걸어서 30분       0.81      0.31      0.44       316
          격기 3반       0.05      0.02      0.02        63
            결계녀       0.74      0.16      0.26       219
   고교생을 환불해 주세요       0.59      0.18      0.28       304
             고수       0.74      0.52      0.61       626
         골든 체인지       1.00      0.05      0.09        41
       공복의 저녁식사       0.84    

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [36]:
result = model.predict([X_test[0],X_test[1],X_test[2],X_test[3], X_test[4]])
result

array(['조의 영역', '뷰티풀 군바리', '그 판타지 세계에서 사는 법', '테러맨', '최강전설 강해효'],
      dtype='<U15')

In [37]:
for idx, category in enumerate(result):
    print(category,':', X_test[idx][:15])

조의 영역 : 풀을 벨때 나는 소리

풀

뷰티풀 군바리 : 다희는 오늘도 예쁘다
그 판타지 세계에서 사는 법 : 자까님 수고하셨구요ㅠ 이거 
테러맨 : 으아ㅏㅏㅏ 초록괴물이다아아아
최강전설 강해효 : 흐흐...이제가볼까?....


In [16]:
str1='쿤쿤 사기쿤'
str2='강룡 최강인거임'
model.predict([str1, str2])

array(['신의 탑', '고수'], dtype='<U15')

In [22]:
model.predict_proba([str1])

array([[8.08616841e-04, 1.52293354e-03, 4.75788598e-04, 1.25168206e-03,
        5.97096505e-04, 1.36274647e-03, 1.61474399e-04, 6.93057012e-04,
        1.48380412e-03, 6.98141817e-05, 1.07480999e-03, 2.85380932e-04,
        8.69000002e-04, 1.03937485e-03, 1.38987012e-03, 1.71756283e-04,
        8.29166465e-04, 3.95112149e-04, 1.05393661e-03, 1.01500783e-03,
        1.90227233e-03, 1.14182678e-03, 2.83005773e-03, 3.96333392e-04,
        3.62530544e-04, 1.78924358e-03, 6.58323879e-04, 2.07694872e-04,
        7.15761845e-04, 4.79764132e-04, 1.16679222e-03, 4.23031559e-04,
        3.26340809e-04, 8.17959503e-04, 5.25570932e-04, 2.15679837e-03,
        2.45055316e-04, 1.57926173e-03, 5.04310280e-04, 8.61094988e-04,
        1.32237310e-03, 6.39981521e-04, 3.42630513e-04, 6.44294020e-04,
        6.90233507e-04, 5.04329941e-05, 1.04868952e-03, 2.64108828e-04,
        7.61481302e-04, 3.05731888e-04, 9.83580499e-04, 1.74590093e-03,
        1.33211581e-03, 2.08794230e-03, 2.95325523e-06, 1.646933

In [38]:
text_df = info_wt.merge(comments, on='wt_num')
text_df = text_df[['user_id','genre','comment']]
X_train, X_test, y_train, y_test = train_test_split(text_df.comment, text_df.genre, \
                                                    test_size = 0.1, random_state =1)
#10%를 테스트로
X_train=X_train.values.astype('U')
X_test=X_test.values.astype('U')



a = Pipeline([
    ('vect', TfidfVectorizer()),
    ('clf', MultinomialNB(alpha=0.01)) # alpha -> 스무딩
])
model = a.fit(X_train, y_train)
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[12537,  2483,    49,  1811,   440,     0,    15,     0,     0,
         1203],
       [ 3992, 10716,    26,  1371,   351,     1,    12,     0,     0,
          960],
       [  521,   346,   336,   227,    71,     0,     3,     0,     0,
          340],
       [ 3671,  1741,    49,  8200,   638,     1,    11,     0,     7,
          902],
       [ 1712,   946,    21,  1164,  2796,     0,     8,     0,    16,
          684],
       [   36,    45,     1,    28,    11,    10,     0,     0,     0,
           73],
       [  276,   148,     7,   150,    55,     0,   201,     0,     0,
           65],
       [   27,     8,     0,    13,     2,     0,     1,     0,     0,
            6],
       [   13,     1,     0,    22,    25,     0,     0,     0,     1,
            1],
       [ 1561,   957,    38,   701,   212,    10,     7,     0,     0,
         8461]])

In [39]:
print(classification_report(y_test, y_pred))


             precision    recall  f1-score   support

     action       0.51      0.68      0.58     18538
      comic       0.62      0.61      0.62     17429
      daily       0.64      0.18      0.28      1844
      drama       0.60      0.54      0.57     15220
    fantasy       0.61      0.38      0.47      7347
 historical       0.45      0.05      0.09       204
       pure       0.78      0.22      0.35       902
sensibility       0.00      0.00      0.00        57
     sports       0.04      0.02      0.02        63
     thrill       0.67      0.71      0.69     11947

avg / total       0.60      0.59      0.58     73551



/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [60]:
str1='남자애들이라고 다를줄 아냐?남자애들도 사람이다.결국 양미정 너의 실체를 알고 떠나갈껄?그리고 남자애들은 진심이 아닌데 눈에 보이는고만 무슨..'
str2='전여친 앞에 속옷깐 경우 그리고 팬티조차없는 주영이 ㅋㅋㅋ'
model.predict([str1, str2])

array(['daily', 'comic'], dtype='<U11')

# CountVectorizer

In [63]:
from sklearn.feature_extraction.text import CountVectorizer
X_train, X_test, y_train, y_test = train_test_split(text_df.comment, text_df.genre, \
                                                    test_size = 0.1, random_state =1)
X_train=X_train.values.astype('U')
X_test=X_test.values.astype('U')

vect = CountVectorizer().fit(X_train)
X_train = vect.transform(X_train)
print("X_train:\n{}".format(repr(X_train)))

X_train:
<661950x1154941 sparse matrix of type '<class 'numpy.int64'>'
	with 5091098 stored elements in Compressed Sparse Row format>


In [64]:
feature_names = vect.get_feature_names()
print("특성 개수: {}".format(len(feature_names)))
print("20010에서 20030까지 특성:\n{}".format(feature_names[20010:20030]))
print("매 2000번째 특성:\n{}".format(feature_names[::20000]))

특성 개수: 1154941
20010에서 20030까지 특성:
['40컷이야', '40컷인', '40컷인건데', '40컷인데', '40컷입니다', '40컷정도면', '40컷평균인데', '40키로고', '40키로대', '40키로대인데', '40키로에', '40키로이럼', '40키론데', '40퍼', '40퍼나되는게', '40퍼넘는', '40퍼넘는데', '40퍼는', '40퍼라는', '40퍼로']
매 2000번째 특성:
['00', '40층에서도', 'xx에x', 'ㅋㅋㅋㅋ한국지리', '갈겨버리면', '개인차인', '경찰님들', '관찰하다니', '그때마다학교있을시간이였어요', '기릿', '꿀꿀이죽', '날린건', '너무했다ㅜㅜ', '뉴미야', '단장은', '더아픈갑다', '되살아나도', '딸이었으면', '리태네', '말잘안하던데', '메너챗', '못하게해', '뮤ㅓㄴ데누군데', '반반도', '버는데에', '보안요소일텐데', '불러보자', '빵구', '산군이라', '생활하는사람', '소녀같이', '슈퍼연근이라', '실제사람들인데', '아ㅋㅋㅋㅋㅋ왜', '안고있는장면은', '알려주샘', '어떻게해서', '여길게', '예민충이라고', '왜구래ㅜㅜ', '워마드가', '이가자그린', '이카르디라는사람', '입고드가냐', '작진', '저랬나보다ㄷㄷ', '정우눈에', '좋아하는게', '지ㄹrㄹ하지마시죠', '집이였자나', '챙겨주면서도', '충족시키고싶은거야', '큭ㅠ', '틀었겟지', '표현의자유가있어', '학업수준부터', '행동을봐', '활자는']
